In [2]:
import pandas as pd
import numpy as np
import psycopg2
from sqlalchemy import create_engine
import io
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Importing the data into the dataframe
df = pd.read_csv("./airline_2m.csv", encoding = "ISO-8859-1")

In [4]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 109 columns):
 #    Column                           Non-Null Count    Dtype
---   ------                           --------------    -----
 0    Year                             2000000 non-null  int64
 1    Quarter                          2000000 non-null  int64
 2    Month                            2000000 non-null  int64
 3    DayofMonth                       2000000 non-null  int64
 4    DayOfWeek                        2000000 non-null  int64
 5    FlightDate                       2000000 non-null  object
 6    Reporting_Airline                2000000 non-null  object
 7    DOT_ID_Reporting_Airline         2000000 non-null  int64
 8    IATA_CODE_Reporting_Airline      2000000 non-null  object
 9    Tail_Number                      1608237 non-null  object
 10   Flight_Number_Reporting_Airline  2000000 non-null  int64
 11   OriginAirportID                  2000000 non-null  int64
 12   OriginAirportSeqID               2000000 non-null  int64
 13   OriginCityMarketID               2000000 non-null  int64
 14   Origin                           2000000 non-null  object
 15   OriginCityName                   2000000 non-null  object
 16   OriginState                      1999354 non-null  object
 17   OriginStateFips                  1999354 non-null  float64
 18   OriginStateName                  1999354 non-null  object
 19   OriginWac                        2000000 non-null  int64
 20   DestAirportID                    2000000 non-null  int64
 21   DestAirportSeqID                 2000000 non-null  int64
 22   DestCityMarketID                 2000000 non-null  int64
 23   Dest                             2000000 non-null  object
 24   DestCityName                     2000000 non-null  object
 25   DestState                        1999406 non-null  object
 26   DestStateFips                    1999406 non-null  float64
 27   DestStateName                    1999406 non-null  object
 28   DestWac                          2000000 non-null  int64
 29   CRSDepTime                       2000000 non-null  int64
 30   DepTime                          1963995 non-null  float64
 31   DepDelay                         1963932 non-null  float64
 32   DepDelayMinutes                  1963932 non-null  float64
 33   DepDel15                         1963932 non-null  float64
 34   DepartureDelayGroups             1963932 non-null  float64
 35   DepTimeBlk                       2000000 non-null  object
 36   TaxiOut                          1584358 non-null  float64
 37   WheelsOff                        1584323 non-null  float64
 38   WheelsOn                         1582042 non-null  float64
 39   TaxiIn                           1582153 non-null  float64
 40   CRSArrTime                       2000000 non-null  int64
 41   ArrTime                          1960449 non-null  float64
 42   ArrDelay                         1958922 non-null  float64
 43   ArrDelayMinutes                  1958922 non-null  float64
 44   ArrDel15                         1958922 non-null  float64
 45   ArrivalDelayGroups               1958922 non-null  float64
 46   ArrTimeBlk                       2000000 non-null  object
 47   Cancelled                        2000000 non-null  float64
 48   CancellationCode                 20220 non-null    object
 49   Diverted                         2000000 non-null  float64
 50   CRSElapsedTime                   1999719 non-null  float64
 51   ActualElapsedTime                1958948 non-null  float64
 52   AirTime                          1580651 non-null  float64
 53   Flights                          2000000 non-null  float64
 54   Distance                         2000000 non-null  float64
 55   DistanceGroup                    2000000 non-null  int64
 56   CarrierDelay                     221803 non-null   float64
 57   WeatherDelay                     221803 non-null   float64
 58   NASDelay                         221803 non-null   float64
 59   SecurityDelay                    221803 non-null   float64
 60   LateAircraftDelay                221803 non-null   float64
 61   FirstDepTime                     4454 non-null     float64
 62   TotalAddGTime                    4454 non-null     float64
 63   LongestAddGTime                  4454 non-null     float64
 64   DivAirportLandings               746114 non-null   float64
 65   DivReachedDest                   1775 non-null     float64
 66   DivActualElapsedTime             1501 non-null     float64
 67   DivArrDelay                      1501 non-null     float64
 68   DivDistance                      1775 non-null     float64
 69   Div1Airport                      1881 non-null     object
 70   Div1AirportID                    1881 non-null     float64
 71   Div1AirportSeqID                 1881 non-null     float64
 72   Div1WheelsOn                     1881 non-null     float64
 73   Div1TotalGTime                   1881 non-null     float64
 74   Div1LongestGTime                 1881 non-null     float64
 75   Div1WheelsOff                    1512 non-null     float64
 76   Div1TailNum                      1514 non-null     object
 77   Div2Airport                      14 non-null       object
 78   Div2AirportID                    14 non-null       float64
 79   Div2AirportSeqID                 14 non-null       float64
 80   Div2WheelsOn                     14 non-null       float64
 81   Div2TotalGTime                   14 non-null       float64
 82   Div2LongestGTime                 14 non-null       float64
 83   Div2WheelsOff                    3 non-null        float64
 84   Div2TailNum                      3 non-null        object
 85   Div3Airport                      0 non-null        float64
 86   Div3AirportID                    0 non-null        float64
 87   Div3AirportSeqID                 0 non-null        float64
 88   Div3WheelsOn                     0 non-null        float64
 89   Div3TotalGTime                   0 non-null        float64
 90   Div3LongestGTime                 0 non-null        float64
 91   Div3WheelsOff                    0 non-null        float64
 92   Div3TailNum                      0 non-null        float64
 93   Div4Airport                      0 non-null        float64
 94   Div4AirportID                    0 non-null        float64
 95   Div4AirportSeqID                 0 non-null        float64
 96   Div4WheelsOn                     0 non-null        float64
 97   Div4TotalGTime                   0 non-null        float64
 98   Div4LongestGTime                 0 non-null        float64
 99   Div4WheelsOff                    0 non-null        float64
 100  Div4TailNum                      0 non-null        float64
 101  Div5Airport                      0 non-null        float64
 102  Div5AirportID                    0 non-null        float64
 103  Div5AirportSeqID                 0 non-null        float64
 104  Div5WheelsOn                     0 non-null        float64
 105  Div5TotalGTime                   0 non-null        float64
 106  Div5LongestGTime                 0 non-null        float64
 107  Div5WheelsOff                    0 non-null        float64
 108  Div5TailNum                      0 non-null        float64
dtypes: float64(72), int64(18), object(19)
memory usage: 1.6+ GB

In [5]:
# Removing unnecessary columns
df2 = df.iloc[:, 0:55]

In [7]:
df2.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 55 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Year                             2000000 non-null  int64
 1   Quarter                          2000000 non-null  int64
 2   Month                            2000000 non-null  int64
 3   DayofMonth                       2000000 non-null  int64
 4   DayOfWeek                        2000000 non-null  int64
 5   FlightDate                       2000000 non-null  object
 6   Reporting_Airline                2000000 non-null  object
 7   DOT_ID_Reporting_Airline         2000000 non-null  int64
 8   IATA_CODE_Reporting_Airline      2000000 non-null  object
 9   Tail_Number                      1608237 non-null  object
 10  Flight_Number_Reporting_Airline  2000000 non-null  int64
 11  OriginAirportID                  2000000 non-null  int64
 12  OriginAirportSeqID               2000000 non-null  int64
 13  OriginCityMarketID               2000000 non-null  int64
 14  Origin                           2000000 non-null  object
 15  OriginCityName                   2000000 non-null  object
 16  OriginState                      1999354 non-null  object
 17  OriginStateFips                  1999354 non-null  float64
 18  OriginStateName                  1999354 non-null  object
 19  OriginWac                        2000000 non-null  int64
 20  DestAirportID                    2000000 non-null  int64
 21  DestAirportSeqID                 2000000 non-null  int64
 22  DestCityMarketID                 2000000 non-null  int64
 23  Dest                             2000000 non-null  object
 24  DestCityName                     2000000 non-null  object
 25  DestState                        1999406 non-null  object
 26  DestStateFips                    1999406 non-null  float64
 27  DestStateName                    1999406 non-null  object
 28  DestWac                          2000000 non-null  int64
 29  CRSDepTime                       2000000 non-null  int64
 30  DepTime                          1963995 non-null  float64
 31  DepDelay                         1963932 non-null  float64
 32  DepDelayMinutes                  1963932 non-null  float64
 33  DepDel15                         1963932 non-null  float64
 34  DepartureDelayGroups             1963932 non-null  float64
 35  DepTimeBlk                       2000000 non-null  object
 36  TaxiOut                          1584358 non-null  float64
 37  WheelsOff                        1584323 non-null  float64
 38  WheelsOn                         1582042 non-null  float64
 39  TaxiIn                           1582153 non-null  float64
 40  CRSArrTime                       2000000 non-null  int64
 41  ArrTime                          1960449 non-null  float64
 42  ArrDelay                         1958922 non-null  float64
 43  ArrDelayMinutes                  1958922 non-null  float64
 44  ArrDel15                         1958922 non-null  float64
 45  ArrivalDelayGroups               1958922 non-null  float64
 46  ArrTimeBlk                       2000000 non-null  object
 47  Cancelled                        2000000 non-null  float64
 48  CancellationCode                 20220 non-null    object
 49  Diverted                         2000000 non-null  float64
 50  CRSElapsedTime                   1999719 non-null  float64
 51  ActualElapsedTime                1958948 non-null  float64
 52  AirTime                          1580651 non-null  float64
 53  Flights                          2000000 non-null  float64
 54  Distance                         2000000 non-null  float64
dtypes: float64(23), int64(17), object(15)
memory usage: 839.2+ MB

In [9]:
# creating dat_dim table
date_dim = df.iloc[:,0:5]
date_dim.insert(4,'quarter', date_dim.pop('Quarter'))

In [11]:
airline_dim = df2.iloc[:, 7:11]
airline_dim.insert(3,'Tail_Number', airline_dim.pop('Tail_Number'))

In [12]:
# changing type to int as DDL has been defined in postgres
origin_dim = df.iloc[:, 11:20]
origin_dim['OriginStateFips'] = origin_dim['OriginStateFips'].fillna(0).astype('int')
origin_dim.pop('Origin')

0          MSP
1          MKE
2          GJT
3          LAX
4          EWR
          ...
1999995    LAS
1999996    EWR
1999997    CHS
1999998    MDW
1999999    IAD
Name: Origin, Length: 2000000, dtype: object

In [13]:
dest_dim = df.iloc[:,20:29]
dest_dim['DestStateFips'] = dest_dim['DestStateFips'].fillna(0).astype('int')
dest_dim.pop('Dest')

0          SLC
1          MCO
2          DFW
3          DTW
4          CLT
          ...
1999995    PHX
1999996    DFW
1999997    CLT
1999998    BNA
1999999    ORD
Name: Dest, Length: 2000000, dtype: object

In [14]:
# changing data type to int where it does not make sense to have a float
time_dim = df.iloc[:,29:47]
# changing the type of columns to int as columns are not really of type float
for i in time_dim.columns.difference(['DepTimeBlk', 'ArrTimeBlk']):
    time_dim[i] = time_dim[i].astype('Int64')

In [15]:
flight_data = df2.iloc[:,[5,6,14,23,47,49,52,54]]
for i in flight_data.columns[4:7]:
    flight_data[i] = flight_data[i].astype('Int64')
flight_data.insert(7,'AirTime', flight_data.pop('AirTime'))
flight_data['date_dim_id'] = range(len(flight_data))
flight_data['airline_dim_id'] = range(len(flight_data))
flight_data['origin_dim_id'] = range(len(flight_data))
flight_data['dest_dim_id'] = range(len(flight_data))
flight_data['time_dim_id'] = range(len(flight_data))

In [33]:
data_tables = [["date_dim",date_dim],
               ["airline_dim",airline_dim],
               ["origin_dim",origin_dim],
               ["dest_dim",dest_dim],
               ["time_dim",time_dim]]

In [ ]:
# creating engine to transfer data to postgres tables
engine = create_engine('postgresql+psycopg2://postgres:password@postgres:5432/metabase')

for table in data_tables:
    conn = engine.raw_connection()
    cur = conn.cursor()
    output = io.StringIO()
    table[1].to_csv(output, sep='\t', header=False, index=True)
    output.seek(0)
    contents = output.getvalue()
    cur.copy_from(output, table[0], null="") # null values become ''
    conn.commit()

In [32]:
flight_data.head()

,FlightDate,Reporting_Airline,Origin,Dest,Cancelled,Diverted,Distance,AirTime,date_dim_id,airline_dim_id,origin_dim_id,dest_dim_id,time_dim_id
0,1998-01-02,NW,MSP,SLC,0,0,991.0,153,0,0,0,0,0
1,2009-05-28,FL,MKE,MCO,0,0,1066.0,141,1,1,1,1,1
2,2013-06-29,MQ,GJT,DFW,0,0,773.0,103,2,2,2,2,2
3,2010-08-31,DL,LAX,DTW,0,0,1979.0,220,3,3,3,3,3
4,2006-01-15,US,EWR,CLT,0,0,529.0,80,4,4,4,4,4

In [35]:
conn = engine.raw_connection()
cur = conn.cursor()
output = io.StringIO()
flight_data.to_csv(output, sep='\t', header=False, index=False)
output.seek(0)
contents = output.getvalue()
cur.copy_from(output, 'flight_data', null="") # null values become ''
conn.commit()